appender.console.filter.0.type = RegexFilter
appender.console.filter.0.regex = (?s).*(Failed to cleanup staging dir|Exception encountered while connecting to the server).*
appender.console.filter.0.onMatch = DENY
appender.console.filter.0.onMismatch = NEUTRAL

logger.yarnclient.name = org.apache.hadoop.yarn.client.api.impl.YarnClientImpl
logger.yarnclient.level = error