spark.master yarn
spark.submit.deployMode client
spark.yarn.archive hdfs:///utils/spark-libs/spark-3.5.7.zip
spark.yarn.stagingDir hdfs://d1mutua-m01.casd.fr:9000/users

spark.serializer org.apache.spark.serializer.KryoSerializer
spark.rdd.compress true

spark.authenticate true
spark.network.crypto.enabled true
spark.io.encryption.enabled true

spark.executor.instances 2
spark.executor.cores 2
spark.executor.memory 2g
spark.executor.memoryOverhead 384m

spark.driver.cores 1
spark.driver.memory 1g
spark.driver.memoryOverhead 384m

spark.sql.adaptive.enabled true
spark.sql.adaptive.coalescePartitions.enabled true
spark.sql.autoBroadcastJoinThreshold 32m

spark.network.timeout 600s
spark.executor.heartbeatInterval 60s

spark.driver.host 192.168.107.200
spark.driver.bindAddress 0.0.0.0

# for using token instead of ticket kerberos
spark.security.credentials.hadoopfs.enabled false
spark.security.credentials.hive.enabled false
spark.security.credentials.hbase.enabled false

# try to remove the warning of missing token
# spark.yarn.security.tokens.hadoopfs.enabled true #deprecated replaced by spark.security.credentials.hadoopfs.enabled
# spark.yarn.security.tokenRenewalInterval 0

spark.hadoop.mapreduce.job.complete.cancel.delegation.tokens false
# spark.yarn.preserve.staging.files true 